FROM python:3.9-slim

WORKDIR /app

COPY . .


RUN python -m pip install --upgrade pip && pip install -r requirements_frontend.txt 


EXPOSE 8000

CMD ["gunicorn", "-w", "4","--bind", "0.0.0.0:8000", "app:app"]