FROM python:3.9-slim

WORKDIR /app

COPY . .

EXPOSE 8000

ENV API_ENDPOINT="http://localhost:8080/predict" \
    FEEDBACK_ENDPOINT="http://localhost:8080/feedback" \
    TIMEOUT_MS="5000" \
    PORT="8000"

CMD python server.py ${PORT}