version: "3.8"

x-minio-env: &minio-env
    MINIO_URL: http://${FIP_OPS}:9000
    MINIO_ACCESS_KEY: minioadmin
    MINIO_SECRET_KEY: minioadmin123

services:
    etl:
        build:
            context: ./etl
            dockerfile: Dockerfile.etl
        environment: *minio-env
        volumes:
            - /mnt/object/etl_data:/app/etl_data
        ports: ["8010:8000"]
        restart: on-failure
        networks: [mlops]

    train:
        build:
            context: ./train
            dockerfile: Dockerfile.train
        environment:
            <<: *minio-env
            DEPLOY_URL: http://${FIP_INFER}:8080
            WANDB_API_KEY: ${WANDB_API_KEY}
            WANDB_BASE_URL: http://${FIP_OPS}:8080
            WANDB_MODE: "online"
            # WANDB_ENTITY: local
            # WANDB_PROJECT: my_project
        volumes:
            - /mnt/object/etl_data:/app/etl_data
            - /mnt/object/models:/app/models
        ports: ["8020:8000"]
        runtime: nvidia
        depends_on: [etl]
        restart: on-failure
        networks: [mlops]

networks:
    mlops:
        driver: bridge
