FROM pytorch/pytorch:2.6.0-cuda12.6-cudnn9-runtime

RUN apt-get update && apt-get install -y git

WORKDIR /app

COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements_train.txt


EXPOSE 8000

CMD ["python", "app.py"] 

