FROM pytorch/pytorch:2.1.2-cuda12.6-cudnn8-runtime

RUN apt-get update && apt-get install -y git

WORKDIR /app

COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENV WANDB_MODE=offline

EXPOSE 8000

CMD ["gunicorn", "-w", "1", "--threads", "4", "-b", "0.0.0.0:8000", "train_app:app"]

