FROM pytorch/pytorch:2.1.2-cuda12.6-cudnn8-runtime

RUN apt-get update && apt-get install -y git

WORKDIR /app

COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements_train.txt

ENV WANDB_MODE=offline

EXPOSE 8000

CMD ["python", "train_app.py"]

