FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN python -m pip install --upgrade pip && pip install --no-cache-dir -r requirements_monitor.txt 

EXPOSE 8000

CMD ["gunicorn",     "--worker-class", "gthread",     "--workers", "1",                "--threads", "16",       "--bind", "0.0.0.0:8000",     "--timeout", "120",     "app:app"]