FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_etl.txt .
RUN pip install --no-cache-dir -r requirements_etl.txt

COPY . .

EXPOSE 8000 


ENV PYTHONUNBUFFERED=1

CMD ["python", "app.py"] 

