# 使用 Python 3.9 作为基础镜像
FROM python:3.11-slim-bullseye

# 设置工作目录
WORKDIR /app

# 安装依赖
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 复制代码
COPY etl_app.py .

# 创建必要的目录
RUN mkdir -p  /app/etl_data

# 暴露端口
EXPOSE 8000 8001

# 启动命令
CMD ["gunicorn", "-w", "1", "--threads", "4", "-b", "0.0.0.0:8000", "etl_app:app"]
